### ISSUE TITLE
Issue with AI

### ISSUE THREAD

**Issue by jfrenl** [vinaymancha/Subway-Surfers-AI#3]
PS G:\DL\Subway-Surfers-AI-master (1)\Subway-Surfers-AI-master> & C:/Users/joche/AppData/Local/Microsoft/WindowsApps/python3.10.exe "g:/DL/Subway-Surfers-AI-master (1)/Subway-Surfers-AI-master/ai.py"
Entering epoch
C:\Users\joche\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\numpy\core\fromnumeric.py:3474: RuntimeWarning: Mean of empty slice. 
  return _methods._mean(a, axis=axis, dtype=dtype,
C:\Users\joche\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\numpy\core\_methods.py:189: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)
Epoch: 1, Average Reward: nan
Entering epoch

**Comment by jfrenl** [comment]
Traceback (most recent call last):
  File "C:\Users\joche\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\pytesseract\pytesseract.py", line 254, in run_tesseract
    proc = subprocess.Popen(cmd_args, **subprocess_args())
    entry = next(self.n_steps_iter)
  File "g:\DL\Subway-Surfers-AI-master (1)\Subway-Surfers-AI-master\experience_replay.py", line 126, in __iter__
    text = pytesseract.image_to_string(pyautogui.screenshot(region = (398,139,137,35)))   #recognizing text to end game
  File "C:\Users\joche\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\pytesseract\pytesseract.py", line 416, in image_to_string    
    return {
  File "C:\Users\joche\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\pytesseract\pytesseract.py", line 419, in <lambda>
    Output.STRING: lambda: run_and_get_output(*args),
  File "C:\Users\joche\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\pytesseract\pytesseract.py", line 286, in run_and_get_output 
    run_tesseract(**kwargs)
  File "C:\Users\joche\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\pytesseract\pytesseract.py", line 258, in run_tesseract      
    raise TesseractNotFoundError()
pytesseract.pytesseract.TesseractNotFoundError: C:\Users\Joche\AppData\Local\Tesseract-OCR\tesseract.exe is not installed or it's not in your PATH. See README file for more information.

**Comment by Error-106** [comment]
maybe your's tesseract.exe not in your PATH? Your's Python can't find it
